# Generated by Django 5.2 on 2025-11-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('condition', models.CharField(max_length=50)),
                ('sustainability_score', models.IntegerField()),
                ('ethical_score', models.IntegerField()),
                ('image_url', models.URLField()),
            ],
        ),
    ]
